Repository prineth/hacktoberfest2022-all, pull requests merged in 2022-10, with the labels that each got.

#5 Update getContributersData.js
  pages/api/getContributersData.js
Labels: hacktoberfest2022

#6 added my detail
  pages/api/getContributersData.js
Labels: hacktoberfest2022

#7 added
  pages/api/getContributersData.js
Labels: hacktoberfest2022

#8 added contributer
  pages/api/getContributersData.js
Labels: hacktoberfest2022

#12 Add yusril-adr
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#16 add: add sofyanmoch into contributor
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#20 Analog Clock
  Analog-Clock/clock (2).PNG
  Analog-Clock/clock.png
  Analog-Clock/index.css
  Analog-Clock/index.html
  Analog-Clock/index.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#17 Added my info
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#18 newUser-fournier
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#21 Added italics to the last statement
  README.md
Labels: hacktoberfest2022, hacktoberfest-accepted

#22 Adding my data into api
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#23 Add Hari sankar
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#24 added a text capitalizer program using javascript
  Other projects/Text_capitalizer_using_javascript.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#25 updating getContributersData.js
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#26 add Data in api
  .vscode/settings.json
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#32 Added Data
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#34 update
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#35 Add my details to getContributersData.js
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#36 update contribute
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#37 add lifanandriand
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#38 Added a form verify program
  Other projects/Form_verify.html
Labels: hacktoberfest2022, hacktoberfest-accepted

#39 Update getContributersData.js
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#41 My Notes Application
  My Notes/README.md
  My Notes/Screenshot (148).png
  My Notes/app.js
  My Notes/index.html
  My Notes/index.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#42 Reg Form Build by Html and CSS
  Reg Form/index.html
  Reg Form/style.css
Labels: hacktoberfest2022, hacktoberfest-accepted

#43 Added Diabetes Predictor in other Project and Modify getcontributorsdata
  Other projects/Diabetes_Predictor/DIABETES.ipynb
  Other projects/Diabetes_Predictor/README.MD
  Other projects/Diabetes_Predictor/diabetes.csv
  pages/api/getContributersData.js
Labels: good first issue, hacktoberfest2022, hacktoberfest-accepted

#44 Update getContributersData.js
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#45 Added the details in `getContributersData.js`
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#48 Added my profile details
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#49 Fixed styling issue & typo in README
  README.md
Labels: good first issue, hacktoberfest2022, hacktoberfest-accepted

#50 Create snake-water-gun.py
  snake-water-gun.py
Labels: hacktoberfest2022, hacktoberfest-accepted

#51 Added my details
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#52 Add contributors
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#53 Updated getContributerData.js file
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#54 Added profile data
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#56 Lowkey-Emmanuel contribution to Hacktoberferst2k22
  pages/api/getContributersData.js
Labels: good first issue, hacktoberfest2022, hacktoberfest-accepted

#57 Added PhilipBDev profile info.
  pages/api/getContributersData.js
Labels: good first issue, hacktoberfest2022, hacktoberfest-accepted

#59 add message
  Analog-Clock/index.html
Labels: hacktoberfest2022, hacktoberfest-accepted

#61 Update getContributersData.js
  pages/api/getContributersData.js
Labels: good first issue, hacktoberfest2022, hacktoberfest-accepted

#63 Update README.md
  README.md
Labels: hacktoberfest2022, hacktoberfest-accepted

#62 QR Code Generator
  QR Code Generator/index.html
  QR Code Generator/script.js
  QR Code Generator/style.css
Labels: hacktoberfest2022, hacktoberfest-accepted

#64 added profile data in getContributersData.js
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#65 Stooge sort
  pages/api/getContributersData.js
  stooge_sort.java
Labels: hacktoberfest2022, hacktoberfest-accepted

#68 Update getContributersData.js
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#69 Create doublyLinkedList
  doublyLinkedList
Labels: hacktoberfest2022, hacktoberfest-accepted

#70 Update getContributersData.js
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#73 Relevant Message
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#71 Update getContributersData.js
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#75 certificate generator added
  Other projects/certificate generator/FileSaver.js
  Other projects/certificate generator/Lato-Light.ttf
  Other projects/certificate generator/certificate.pdf
  Other projects/certificate generator/index.html
  Other projects/certificate generator/index.js
  Other projects/certificate generator/style.css
Labels: hacktoberfest2022, hacktoberfest-accepted

#76 Update getContributersData.js
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#77 Update getContributersData.js
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#78 Update getContributersData.js
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#81 Create index.html
  Other projects/Credit-Card/index.html
Labels: good first issue, hacktoberfest2022, hacktoberfest-accepted

#80 Create style.css
  Other projects/Credit-Card/style.css
Labels: hacktoberfest2022, hacktoberfest-accepted

#82 Update getContributersData.js
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#83 Add files via upload
  AllotWaterCommand.java
  BillService.java
Labels: hacktoberfest2022, hacktoberfest-accepted

#84 Update getContributersData.js
  pages/api/getContributersData.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#86 Created new folder Python_snippet
  Other projects/Python_snippets/db_connection_sqlite3.py
  Other projects/Python_snippets/file_name_collector.py
Labels: hacktoberfest2022, hacktoberfest-accepted

#87 Added new snippet to the folder
  Other projects/Python_snippets/csv_to_panda_df.py
Labels: hacktoberfest2022, hacktoberfest-accepted

#88 Added new snippet to the folder
  Other projects/Python_snippets/create_a_pickle_object.py
Labels: hacktoberfest2022, hacktoberfest-accepted

#90 Nav Bar
  Other projects/Nav Bar/Nav.html
Labels: hacktoberfest2022, hacktoberfest-accepted

#89 merge 2 BST
  Other projects/merge 2 BST
Labels: hacktoberfest2022, hacktoberfest-accepted
